AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: runAdoya entry point.
Resources:
  runAdoya:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: runAdoya.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 448
      Timeout: 900
      FunctionName: 'runAdoya'
      Role: 'arn:aws:iam::496475828721:role/service-role/lambda_dynamo'
  runAdoyaWeekly:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: runAdoyaWeekly.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 448
      Timeout: 900
      FunctionName: 'runAdoyaWeekly'
      Role: 'arn:aws:iam::496475828721:role/service-role/lambda_dynamo'
  ClientHistory:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getClientHistory.lambda_handler
      Runtime: python3.7
      CodeUri: ./api
      Description: ''
      MemorySize: 448
      Timeout: 60
      FunctionName: 'ClientHistory'
      Role: 'arn:aws:iam::496475828721:role/service-role/lambda_dynamo'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /client/history
            Method: get
  Admin:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: postAdmin.lambda_handler
        Runtime: python3.7
        CodeUri: ./api
        Description: ''
        MemorySize: 448
        Timeout: 60
        FunctionName: 'Admin'
        Role: 'arn:aws:iam::496475828721:role/service-role/lambda_dynamo'
        Events:
          Api:
            Type: Api
            Properties:
              Path: /admin
              Method: post
