AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  runAdoyaTest:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: runBranchIntegration.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 448
      Timeout: 60
      Role: 'arn:aws:iam::496475828721:role/service-role/lambda_dynamo'
