AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: runAdoya entry point.
Resources:
  runAdoya:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: runAdoya.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 448
      Timeout: 480
      FunctionName: 'runAdoya'
      Role: 'arn:aws:iam::496475828721:role/service-role/lambda_dynamo'
#  runBranchIntegration:
#    Type: 'AWS::Serverless::Function'
#    Properties:
#      Handler: runBranchIntegration.lambda_handler
#      Runtime: python3.7
#      CodeUri: .
#      Description: ''
#      MemorySize: 448
#      Timeout: 60
#      FunctionName: 'runBranchIntegration'
#      Role: 'arn:aws:iam::496475828721:role/service-role/lambda_dynamo'
