AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: runAdoya entry point.
Globals:
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'x-api-key,Content-Type'"
      AllowOrigin: "'*'"
Resources:
  runAdoyaNightly:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: runAdoyaNightly.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 900
      FunctionName: "runAdoyaNightly"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
  runClient:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: runClient.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 1000
      Timeout: 900
      FunctionName: "runClient"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      EventInvokeConfig:
        MaximumRetryAttempts: 0
  runAdoyaBiweekly:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: runAdoyaBiweekly.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 1000
      Timeout: 900
      FunctionName: "runAdoyaBiweekly"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      EventInvokeConfig:
        MaximumRetryAttempts: 0
  runAdoyaWeekly:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: runAdoyaWeekly.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 900
      FunctionName: "runAdoyaWeekly"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
  postClientAdmin:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: clientApi.postClientAdminHandler
      Runtime: python3.7
      CodeUri: .
      Description: "Internal use 'shortcut' endpoint for admins, supports read, update, delete, & list operations on any table"
      MemorySize: 448
      Timeout: 60
      FunctionName: "postClientAdmin"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/client/admin
            Method: post
  getClientKeywordHistory:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: clientApi.getClientKeywordHistoryHandler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 60
      FunctionName: "getClientKeywordHistory"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/client/keyword/history/
            Method: GET
            Auth:
              ApiKeyRequired: true
  getClientCostHistory:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: clientApi.getClientCostHistoryHandler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 60
      FunctionName: "getClientCostHistory"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/client/cost/history
            Method: GET
            Auth:
              ApiKeyRequired: true
  postSupportItem:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: supportApi.postSupportItemHandler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 60
      FunctionName: "postSupportItem"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/support/post
            Method: ANY
            Auth:
              ApiKeyRequired: true
  postClient:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: clientApi.postClientHandler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 60
      FunctionName: "postClient"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/client/post
            Method: ANY
            Auth:
              ApiKeyRequired: true
  getAppleApps:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: appleApi.getAppleApps
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 60
      FunctionName: "getAppleApps"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/apple/apps
            Method: ANY
            Auth:
              ApiKeyRequired: true
  getClient:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: clientApi.getClientHandler
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 60
      FunctionName: "getClient"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/client/get
            Method: GET
            Auth:
              ApiKeyRequired: true
  getAppleAcls:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: appleApi.getAppleAcls
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 60
      FunctionName: "getAppleAcls"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/apple/acls
            Method: ANY
            Auth:
              ApiKeyRequired: t
  postAppleCampaign:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: appleApi.postAppleCampaign
      Runtime: python3.7
      CodeUri: .
      Description: ""
      MemorySize: 448
      Timeout: 900
      FunctionName: "postAppleCampaign"
      Role: "arn:aws:iam::496475828721:role/service-role/lambda_dynamo"
      Environment:
        Variables:
          env: "prod"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/apple/campaign
            Method: ANY
            Auth:
              ApiKeyRequired: true
